version: '3'

vars:
  APP_NAME: ConfigLens
  SPEC_FILE: config-lens.spec
  APP_PATH: dist/{{.APP_NAME}}.app

tasks:
  default:
    desc: 使用可能なタスクを表示
    cmds:
      - task --list

  install:
    desc: 依存関係をインストール
    cmds:
      - uv sync

  build:
    desc: リリースビルド
    cmds:
      - pyinstaller --noconfirm {{.SPEC_FILE}}

  clean:
    desc: クリーンビルド
    cmds:
      - rm -rf build dist
      - pyinstaller --noconfirm {{.SPEC_FILE}}

  # アドホック署名（移動可能にする）
  sign:
    desc: アプリケーションにアドホック署名
    deps: [build]
    cmds:
      - codesign --force --deep --sign - {{.APP_PATH}}
      - echo "アドホック署名完了"

  # 署名の検証
  verify:
    desc: アプリケーションの署名を検証
    cmds:
      - codesign --verify --deep --verbose=2 {{.APP_PATH}}
      - spctl --assess --verbose=4 {{.APP_PATH}}

  # 署名してビルド
  build-signed:
    desc: ビルドしてアドホック署名
    cmds:
      - task: build
      - task: sign

  # 隔離属性を削除（Gatekeeper回避）
  remove-quarantine:
    desc: Gatekeeper の隔離属性を削除
    cmds:
      - xattr -cr {{.APP_PATH}}
      - echo "隔離属性を削除しました"

  # 配布用にDMGを作成
  create-dmg:
    desc: 配布用のDMGファイルを作成
    deps: [build-signed]
    cmds:
      - mkdir -p dist/dmg
      - cp -R {{.APP_PATH}} dist/dmg/
      - hdiutil create -volname "{{.APP_NAME}}" -srcfolder dist/dmg -ov -format UDZO dist/{{.APP_NAME}}.dmg
      - rm -rf dist/dmg


  run:
    desc: ビルドして実行
    deps: [build]
    cmds:
      - open {{.APP_PATH}}

  dev-build:
    desc: デバッグビルド
    cmds:
      - cp {{.SPEC_FILE}} {{.SPEC_FILE}}.bak
      - sed -i '' 's/debug=False/debug=True/' {{.SPEC_FILE}}
      - sed -i '' 's/console=False/console=True/' {{.SPEC_FILE}}
      - pyinstaller --noconfirm {{.SPEC_FILE}}
      - mv {{.SPEC_FILE}}.bak {{.SPEC_FILE}}

  run-debug:
    desc: デバッグビルドを実行
    deps: [dev-build]
    cmds:
      - ./{{.APP_PATH}}/Contents/MacOS/{{.APP_NAME}}

  lint:
    desc: リンターでコードチェック
    cmds:
      - uv run ruff check src/
      - uv run ruff format --check src/

  lint-fix:
    desc: リンターで自動修正
    cmds:
      - uv run ruff check --fix src/
      - uv run ruff format src/

  type-check:
    desc: 型チェック実行
    cmds:
      - uv run pyright src/

  test:
    desc: テスト実行
    cmds:
      - uv run pytest

  test-verbose:
    desc: テスト実行（詳細表示）
    cmds:
      - uv run pytest -v

  test-cov:
    desc: カバレッジ付きでテスト実行
    cmds:
      - uv run pytest --cov=src --cov-report=html --cov-report=term

  check:
    desc: すべてのチェック実行
    deps: [lint, type-check, test]

  init:
    desc: プロジェクトの初期化
    cmds:
      - uv sync

  clean-all:
    desc: すべてのビルドファイルとキャッシュを削除
    cmds:
      - rm -rf build dist
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
      - find . -type d -name "*.egg-info" -exec rm -rf {} +
      - find . -type d -name ".pytest_cache" -exec rm -rf {} +
      - find . -type d -name ".ruff_cache" -exec rm -rf {} +

  setup:
    desc: 開発環境をセットアップ
    cmds:
      - task: install
      - task: init
      - echo "開発環境のセットアップが完了しました"